# Generated by Django 2.2.1 on 2019-08-11 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=255)),
                ('startTime', models.DateTimeField(auto_now_add=True)),
                ('endTime', models.DateTimeField(default=datetime.datetime(2019, 8, 11, 11, 16, 36, 786926))),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
        ),
    ]
