# Generated by Django 2.2.1 on 2019-08-11 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20190811_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='deals',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 11, 16, 53, 740015)),
        ),
    ]
